### ISSUE TITLE
Sponsor button shows some error.

### ISSUE THREAD

**Issue by imvetri** [panphora/remake#11]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by imvetri** [comment]
<img width="464" alt="Screen Shot 2020-01-20 at 3 03 51 PM" src="https://user-images.githubusercontent.com/6542274/72715287-347d9500-3b96-11ea-94f9-0ebba6d418e5.png">

**Comment by panphora** [comment]
Thank you for calling my attention to this! I'm getting it sorted now!

**Comment by panphora** [comment]
@imvetri Thank you for reporting this. I just got approved for GitHub Sponsors 4 days ago, so it should be fixed now!
